// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://rqxswavurupakgdesncl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxeHN3YXZ1cnVwYWtnZGVzbmNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNzMxMDMsImV4cCI6MjA2MTY0OTEwM30.PiLrocYRGGX0Tic5ayFkT_Fdzj4h0wDFQlzGliCsMwg";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
